output_dir: null

dataset:
  name: cifar10
  data_path: ./data/CIFAR10
  img_size: 32
  rand_aug: false

networks:
  def_file: ./models/ResNet.py
  params: {m_type: 'resnet18', cls_type: 'fc', num_classes: 10}

strategy:
  train_type: 'bpfc'   # baseline / mixup / bpfc
  test_type: 'baseline' 

attacker_opt:
  adv_val: false          # Adversarial attack during inference
  adv_train: false        # Adversarial training
  attack_type: 'FGSM'     # Adversarial attack algorithm type, candidates: 'PGD', 'PGDL2', 'FGSM', 'FFGSM', 'GN', 'UN'
  attack_set: 'setting1'  # attack setting is under attacker_config.yaml 
  eot_iter: 1             # EOT version of attacker is applied when eot_iter > 1 

training_opt:
  num_epochs: 110
  batch_size: 128
  data_workers: 4
  optimizer: 'SGD'  # 'Adam' / 'SGD'
  optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
  scheduler: 'step' # 'cosine' / 'step'
  scheduler_params: {endlr: 0.0, gamma: 0.1, milestones: [10, 100, 105]}

bpfc_opt:
  p_val: 5               # (k in paper) 5,6,7 for cifar10, FMNIST, MNIST
  w_ce: 1                # cross entropy loss weight
  w_reg: 1               # regression loss weight
  mul_ru: 9              # regression weight multiplier
  milestones: [25,50,75]      # update w_reg by mul_ru at K-th epoch

test_opt:                        
  save_data: false               # for val
  file_name: 'adv_images.pth'    # for val
  save_length: 5                 # only save first 10 batch for efficiency


logger_opt:
  print_grad: false
  print_iter: 100

checkpoint_opt:
  save_best: true          # only save the model that better than previous epoches (except the last epoch)
  checkpoint_step:  10
  checkpoint_name: 'test_model.pth'